repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        exclude: ^bootstrap/
      - id: terraform_validate
        exclude: ^bootstrap/
      - id: terraform_tflint
        exclude: ^bootstrap/
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
